services:
  - type: web
    name: nuvem-shop-udi-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
    plan: free
    region: oregon
